utility for generating parameter table for wiki.
JASMINE-Mission/jasmine_toolkit pull request #6
Opened 2023-07-11 13:23 UTC by yamadayy

2023-07-11 21:15 UTC, yamadayy commented
This is the code for generating parameter table. Also parameter table in E2E name space of wiki is updated.

2023-07-19 10:33 UTC, astronasutarou requested changes
目的を考えると物理定数などは出力に含めないほうが良いかと思います．出力についてもコメントしましたが今回は別にいいかなという気もします．

2023-07-19 10:33 UTC, astronasutarou commented on jasmine_toolkit/utils/parameter_table.py
> +    p.ONE_YEAR,
これらはテーブルに出力しなくてもいいように思います．

2023-07-19 10:33 UTC, astronasutarou commented on jasmine_toolkit/utils/parameter_table.py
> +            write_without_name_item(fp, i)
`v_list` と `i` は常にセットで使われているようなので `v_list` の中身で for を回したほうがシンプルにならないでしょうか？以下のようなイメージです．

``` python
for v in v_list:
  if isinstance(v, JasmineConstant):
    write_jasmine_constant(v)
  elif isinstance(v, list):
    write_without_name_item(v)
  else:
    raise ValueError(f'wrong item type {type(v)}')
```

2023-07-19 10:33 UTC, astronasutarou commented on jasmine_toolkit/utils/parameter_table.py
> +    write_to_file("tmp.txt")
1. 標準出力からのコピペで十分かと思いましたがファイルに書いたほうがいいでしょうか．
2. ローカルに `tmp.txt` があると上書きしてしまうのでファイル名のハードコードは避けたほうがいいと思います．ハードコードする場合には安易に上書きされないような安全装置が欲しいですね．

2023-07-19 13:10 UTC, yamadayy commented on jasmine_toolkit/utils/parameter_table.py
> +    write_to_file("tmp.txt")
出力が長いのでファイルにしました。また、これは臼井さん(かサーバーの管理権限がある人)の仕事ですが、将来は手動コピーではなくwikiの中の決まった名前のファイルに定期的に上書きしてゆくという運用になるはずなので、既存ファイルに上書きが良いと思いました。従って直していません。

2023-07-19 13:10 UTC, yamadayy commented on jasmine_toolkit/utils/parameter_table.py
> +            write_without_name_item(fp, i)
修正しました

2023-07-19 13:10 UTC, yamadayy commented on jasmine_toolkit/utils/parameter_table.py
> +    p.ONE_YEAR,
削除しました

2023-07-20 01:50 UTC, astronasutarou approved these changes
Approved.

2023-07-20 02:33 UTC, merged